# Site settings
title: Stanford Raagapella
email: business@raagapella.com
description: > # this means to ignore newlines until "baseurl:"
  Raagapella is Stanford's all-male South Asian a cappella group.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raagapella.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
